### ISSUE TITLE
when webhook run it fails with following error  'api' is not defined

### ISSUE THREAD

**Issue by vimtechnologies** [TheHive-Project/TheHive4py#134]
Bug 

### Work Environment ###

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 
| TheHive4py version / git hash   | 

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. Install thehivehooks
1. Install thehive4py
1. thehive hook return an error when api.run_analyzer run 

### Complementary information
[2019-12-11 15:08:09,046] WARNING in handlers: Case with object type 10.10.10.0
[2019-12-11 15:15:43,425] WARNING in handlers: Case with object type 8.8.8.8
[2019-12-11 15:23:22,987] WARNING in handlers: Case with object type test.pdf
[2019-12-11 15:23:23,004] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/TheHiveHooks/thehive_hooks/controllers.py", line 21, in webhook
    ee.emit(event_name, event)
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/pyee/_base.py", line 102, in emit
    self._emit_run(f, args, kwargs)
  File "/opt/TheHiveHooks/venv/lib/python3.7/site-packages/pyee/_compat.py", line 48, in _emit_run
    coro = f(*args, **kwargs)
  File "/opt/TheHiveHooks/thehive_hooks/handlers.py", line 51, in CaseArtifactCreation
    api.run_analyzer(cortexServerId, ObsId, analyzerId)
NameError: name 'api' is not defined

**Comment by nadouani** [comment]
Hello, this not a TheHive4py related issue, but it related to the code you have in your TheHiveHooks instance.
