### ISSUE TITLE
Error with models.py when running test scripts

### ISSUE THREAD

**Issue by lewOc** [TheHive-Project/TheHive4py#186]
### Request Type
BUG

Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 18
| TheHive4py version / git hash   |  V1.7.2 Python version 3

### Problem Description
Traceback (most recent call last):
  File "test_alert.py", line 20, in <module>
    AlertArtifact(dataType='file', data='pic.png'),
  File "/usr/local/lib/python3.6/dist-packages/thehive4py/models.py", line 577, in __init__
    self.data = self._prepare_file_data(attributes.get('data', None))
  File "/usr/local/lib/python3.6/dist-packages/thehive4py/models.py", line 582, in _prepare_file_data
    with open(file_path, "rb") as file_artifact:
FileNotFoundError: [Errno 2] No such file or directory: 'pic.png'

### Steps to Reproduce
1. Install Hive4py with pip
1. Run alert creation test script
1. receive error

### Possible Solutions
API key has been added and no edits have been made to scripts

**Comment by lewOc** [comment]
I simply didn't download the entire directory. User error
