### ISSUE TITLE
 SSLError

### ISSUE THREAD

**Issue by novitski** [TheHive-Project/TheHive4py#77]
Hello,

I use thehive4py for alerting on thehive from RSA SIEM.

Thehive url is usign ssl, and i have this error : 

Create Alert
-----------------------------
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 827, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests-2.18.4-py3.5.egg/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.84.10.10', port=443): Max retries exceeded with url: /api/alert (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/thehive4py-1.4.3-py3.5.egg/thehive4py/api.py", line 349, in create_alert
  File "/usr/local/lib/python3.5/site-packages/requests-2.18.4-py3.5.egg/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests-2.18.4-py3.5.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests-2.18.4-py3.5.egg/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.80.X.X', port=443): Max retries exceeded with url: /api/alert (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "test_alerte.py", line 121, in <module>
    thehive()
  File "test_alerte.py", line 109, in thehive
    response = api.create_alert(thehivealert)
  File "/usr/local/lib/python3.5/site-packages/thehive4py-1.4.3-py3.5.egg/thehive4py/api.py", line 351, in create_alert
thehive4py.exceptions.AlertException: Alert create error: HTTPSConnectionPool(host='10.80.X.X', port=443): Max retries exceeded with url: /api/alert (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
```

**Comment by 3c7** [comment]
Your python version was compiled without SSL modules. Prior to compiling python you need the openssl-dev package.

**Comment by nadouani** [comment]
I don't think this is an issue with `TheHive4py` but with the certificate or your python install. 

Honestly, there is nothing to do using `request`.
